var vue = new Vue({ 
  data: {
    lem:[
{formula: "",
print: "",
form_chn: "",
class1: "",
class2: "",
class3: "",
descript1: "",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},

      
      
      

//力学
//运动学
{formula: " x=vt s=vt v=x/t v=s/t匀速直线运动位移公式 速度 位移",
print: "x=vt",
form_chn: "匀速直线运动位移公式",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " x:位移<br>v:速度<br>t:时间",
descript2: "匀速直线运动的物体位移等于它的速度乘时间",
photo: "",
apply: "", 
de: "",
eg_q: "木块以5m/s沿直线向前滑行，滑行3s，请问滑行多远？",
eg_a: " x=vt=5m/s×3s=15m",
},

{formula: "x=v0t+1/2at2, x=vt+1/2at2, 匀加速直线运动位移公式",
print: "x=v<sub>0</sub>t+(1/2)at<sup>2</sup>",
form_chn: "匀加速直线运动位移公式",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " x:位移<br>v<sub>0</sub>:初速度<br>t:时间<br>a:加速度",
descript2: "",
photo: "",
apply: "", 
de: " x=∫vdt=∫(v<sub>0</sub>+at)dt=v<sub>0</sub>t+(1/2)at<sup>2</sup>",
eg_q: "木块以5m/s的初速度沿直线向前滑行,加速度为1m/s<sup>2</sup>,滑行3s,请问滑行多远?",
eg_a: "x<br>=v<sub>0</sub>t+1/2at<sup>2</sup><br>=5m/s×3s +1/2×1m/s<sup>2</sup>×(3s)<sup>2</sup <br>=19.5m ",
},


{formula: "vt=v0+at v=v0+at匀加速直线运动速度公式",
print: "v<sub>t</sub>=v<sub>0</sub>+at",
form_chn: "匀加速直线运动速度公式",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " v<sub>t</sub>:末速度<br>v<sub>0</sub>:初速度<br>t:时间<br>a:加速度",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "木块以5m/s的初速度沿直线向前滑行，加速度为1m/s<sup>2</sup>，请问滑行3s后速度大小是多少?",
eg_a: " v<sub>t</sub><br>= v<sub>0</sub>+at<br>=5m/s+1m/s<sup>2</sup>×3s<br>=8m/s ",
},


{formula: " x=1/2(v0+vt)t  x= (v0+vt) /2t 匀加速直线运动位移公式",
print: "x=(v<sub>0</sub> + v<sub>t</sub>)/2t ",
form_chn: "匀加速直线运动位移公式",
class1: "力学",
class2: "运动学",
class3: "",
descript1: "x:位移<br>v<sub>0</sub>:初速度<br>v<sub>t</sub>:末速度<br>t:时间",
descript2: "",
photo: "",
apply: "", 
de: " x <br>= v<sub>0</sub>t+(1/2)at<sup>2</sup> <br>=(1/2) v<sub>0</sub>t+1/2 v<sub>0</sub>t+(1/2)at<sup>2</sup> <br>=(1/2)t(v<sub>0</sub>+v<sub>0</sub>+at) <br>=(1/2) (v<sub>0</sub>+ v<sub>t</sub>)t",
eg_q: "木块以5m/s的初速度沿直线匀加速向前滑行，3s后速度变为8m/s，请问木块滑行多远？",
eg_a: " x<br>=(1/2)(v<sub>0</sub> + v<sub>t</sub>)t<br>=1/2×(5m/s+8m/s)×3s<br>=19.5m ",
},


{formula: "x=vtt-1/2at2 x=vt-1/2at2匀加速直线运动位移公式",
print: "x= v<sub>t</sub>t-(1/2)at<sup>2</sup>",
form_chn: "匀加速直线运动位移公式",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " x:位移<br> v<sub>t</sub>:末速度<br>t:时间<br>a:加速度",
descript2: "",
photo: "",
apply: "", 
de: "x <br>= v<sub>0</sub>t+1/2a t<sup>2</sup> <br>= v<sub>0</sub>t+ a t<sup>2</sup>-1/2a t<sup>2</sup> <br>= t(v<sub>0</sub>+at)-1/2a t<sup>2</sup> <br>= v<sub>t</sub>t-1/2a t<sup>2</sup>",
eg_q: "木块沿直线向前滑行，加速度为1m/s<sub>2</sub>，滑行3后速度为8m/s，请问木块滑行多远",
eg_a: " x <br>= v<sub>t</sub>t-1/2a t<sup>2</sup> <br>=8m/s×3s-(1/2)×1m/s<sup>2</sup>×(3s) <sup>2</sup> <br>=19.5m ",
},


{formula: " h=1/2gt2, h=gt2/2, t=2h/g, 自由落体 高度 时间",
print: "h=gt<sup>2</sup>/2, t=√(2h/g)",
form_chn: "自由落体",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " h:下落高度<br>g:重力加速度<br>t:时间",
descript2: "自由落体的物体下落高度是重力加速度与时间的平方乘积的一半",
photo: "",
apply: "", 
de: " x= v<sub>0</sub>t+1/2a t<sup>2</sup> <br>自由落体时x=h, v<sub>0</sub>=0, a=g <br>故h=gt<sup>2</sup>/2",
eg_q: "小球从楼上自由落下，3s落地，请问楼有多高?",
eg_a: "h <br>=1/2g t<sup>2</sup> <br>=1/2×10m/ s<sup>2</sup>×(3 s)<sup>2</sup> <br>=45m ",
},


{formula: " v=gt , vt=gt, 自由落体速度公式",
print: "v<sub>t</sub>=gt",
form_chn: "自由落体速度公式",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " v<sub>t</sub> :末速度<br> g:重力加速度<br> t:时间",
descript2: "自由落体的物体下落的末速度是重力加速度乘时间",
photo: "",
apply: "", 
de: " v<sub>t</sub> =v<sub>0</sub> +at <br>自由落体时v<sub>0</sub> =0, a=g <br>故v<sub>t</sub> =gt ",
eg_q: "小球从楼上自由落下，3s落地，请问落地时速度大小是多少?",
eg_a: "v<sub>t</sub> <br> =gt<br> =10m/s<sup>2</sup>×3s<br> =30m/s ",
},


{formula: "x2=(vx0t)2+(vy0t+1/2gt2)2, x2=(vxt)2+(vyt+1/2gt2)2, 抛体运动位移",
print: "x<sup>2</sup>=(v<sub>x0</sub> t) <sup>2</sup>+(v<sub>y0 </sub>t+gt<sup>2</sup>/2)<sup>2</sup>",
form_chn: "抛体运动位移",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " x:位移<br> g:重力加速度<br> vy0:竖直方向初速度<br> v<sub>x0</sub>:水平方向初速度<br> t:时间",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "小球以斜向上37度以5m/s的速度抛出,请问3s后小球位移是多少?不计空气阻力",
eg_a: " v<sub>y0 </sub>= v<sub>0</sub>sin37=3m/s <br>v<sub>x0</sub>= v<sub>0</sub>cos37=4m/s <br>x <sup>2</sup><br>=(v<sub>x0</sub>)<sup>2</sup>+( v<sub>y0 </sub>+1/2g t<sup>2</sup>)<sup>2</sup> <br>=(4m/s×3s) <sup>2</sup>+[3m/s×3s+1/2×10m/s<sup>2</sup>×(3s) <sup>2</sup>]<sup>2</sup> <br>=(55.32m) <sup>2</sup> <br>x=55.32m",
},


{formula: "2ax=vt2-v02, 匀加速直线运动 位移与速度关系",
print: "2ax=v<sub>t</sub><sup>2</sup>-v<sub>0</sub><sup>2</sup>",
form_chn: "匀加速直线运动 位移与速度关系",
class1: "力学",
class2: "运动学",
class3: "",
descript1: " v<sub>t</sub>:末速度<br>v<sub>0</sub>:初速度<br>x:位移<br>a:加速度",
descript2: "",
photo: "",
apply: "", 
de: "v=v<sub>0</sub>+at,<br>v<sup>2</sup>=v<sub>0</sub><sup>2</sup>+a<sup>2</sup>t<sup>2</sup>+2v<sub>0</sub>at,<br>v<sup>2</sup>-v<sub>0</sub><sup>2</sup><br>=at(v-v<sub>0</sub>)+2v<sub>0</sub>at<br>=at(v+v<sub>0</sub>)<br>=2ax",
eg_q: "",
eg_a: "",
},


{formula: " x＝aT2 , s=at2, 匀加速直线运动相邻等时间内位移差",
print: "Δx＝aT<sup>2</sup>",
form_chn: "匀加速直线运动相邻等时间内位移差",
class1: "力学",
class2: "运动学",
class3: "",
descript1: "T:时间间隔 <br>Δx: 任意两段相邻时间间隔内两段位移的差<br> a:加速度",
descript2: "",
photo: "",
apply: "", 
de: "v<sub>1</sub> = v<sub>0</sub> + aT<br>x<sub>1</sub> = v<sub>0</sub>T + 1/2 aT<sup>2</sup><br>x<sub>2</sub> = v<sub>1</sub>T + 1/2 aT<sup>2</sup><br>Δx <br>= x<sub>2</sub> - x<sub>1</sub><br>= T(v<sub>1</sub> - v<sub>0</sub>)<br>= T(v<sub>0</sub>+ aT - v<sub>0</sub>)<br>= aT<sup>2</sup>",
eg_q: "",
eg_a: "",
},


//牛顿第二定律
{formula: "F=ma, a=F/m, 牛顿第二定律",
print: "F=ma",
form_chn: "牛顿第二定律",
class1: "力学",
class2: "",
class3: "",
descript1: "F: 合力;<br> m:质量;<br> a:加速度",
descript2: "物体所受到的合外力等于它的质量乘加速度",
photo: "",
apply: "宏观低速运动", 
de: "F <br>= p/t <br>= mv/t <br>=ma",
eg_q: "处于粗糙水平面1kg的物体受到水平向右3N的拉力, 反方向同时受到1N的滑动摩擦力。它的加速度是多少？",
eg_a: "2m/s<sub>2</sub>",
},

{formula: "F=p/t牛顿第二定律",
print: "F=p/t",
form_chn: "牛顿第二定律(原始表述)",
class1: "力学",
class2: "",
class3: "",
descript1: "F:合力;<br>p:动量;<br> t:时间",
descript2: "牛顿第二定律常见的表述为F=ma ",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},



//圆周运动
{formula: "F=mv2/r, F=mw2r, 圆周运动向心力",
print: "F=mv<sup>2</sup>/r, F=mω<sup>2</sup>r",
form_chn: "圆周运动向心力",
class1: "力学",
class2: "圆周运动",
class3: "",
descript1: " F:向心力<br> m:质量<br> r:半径<br> v:线速度<br>ω:角速度",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "质量为2kg的小球以3m/s的线速度被绳子拉着做匀速圆周运动，绳长1m，请问小球受到向心力有多大？",
eg_a: " F=mv<sup>2</sup>/r=2×3<sup>2</sup>/1=18N",
},


{formula: "a=v2/r, a=w2r, 圆周运动向心加速度",
print: "a=v<sup>2</sup>/r, a=ω<sup>2</sup>r ",
form_chn: "圆周运动向心加速度",
class1: "力学",
class2: "圆周运动",
class3: "",
descript1: "a:向心加速度<br> r:半径<br> v:线速度<br>ω:角速度",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//常见的力
{formula: "f/N, f=μFN, f=μN, f=μF, 滑动摩擦力",
print: "f=μN",
form_chn: "滑动摩擦力",
class1: "力学",
class2: "",
class3: "",
descript1: "f:滑动摩擦力<br>μ:动摩擦因数<br>N: 对接触面的压力",
descript2: "滑动摩擦力方向与物体相对运动方向相反",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "G=mg 重力",
print: "G=mg ",
form_chn: "重力",
class1: "力学",
class2: "",
class3: "",
descript1: "G: 重力<br>m:质量<br>g: 重力加速度, 约9.8m/s<sup>2</sup>",
descript2: "重力方向竖直向下",
photo: "",
apply: "适用于地球表面附近", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "F=-kx, F=kx 胡克定律 弹簧拉力 弹簧弹力 劲度系数 倔强系数",
print: "F=-kx",
form_chn: "胡克定律",
class1: "力学",
class2: "",
class3: "",
descript1: "k:劲度系数/倔强系数(N/m)<br>x:形变量<br>F:力<br>负号表示弹簧所产生的弹力与其伸长/压缩的方向相反",
descript2: "在材料的线弹性范围内，固体的形变量与所受的外力成正比",
photo: "",
apply: "在材料的线弹性范围内", 
de: "",
eg_q: "",
eg_a: "",
},


//力矩
{formula: "F1L1=F2L2杠杆原理 杠杆定理",
print: "F<sub>1</sub>L<sub>1</sub>=F<sub>2</sub>L<sub>2</sub>",
form_chn: "杠杆原理",
class1: "力学",
class2: "力矩",
class3: "",
descript1: "F1:动力<br>L1:动力臂<br>F2:阻力<br>L2:阻力臂",
descript2: "",
photo: "gangganyuanli.png",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "M=r×F, M=rFsinθ力矩 杠杆原理",
print: "M=r×F",
form_chn: "力矩",
class1: "力学",
class2: "",
class3: "",
descript1: "M:力矩(矢量)<br>r: 从转动轴到着力点的距离<br>F:力",
descript2: "力矩等于径向矢量与作用力的叉积，大小为M=rFsinθ",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//动量
{formula: "p=mv 动量",
print: "p=mv",
form_chn: "动量",
class1: "力学",
class2: "动量",
class3: "",
descript1: " p: 动量<br>m: 质量<br>v: 速度",
descript2: "物体的质量m和速度v的乘积叫做动量, 动量的方向和速度的方向相同",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "I=Ft冲量",
print: "I=Ft",
form_chn: "冲量",
class1: "力学",
class2: "动量",
class3: "",
descript1: "I: 冲量<br>F: 力<br>t: 力的作用时间",
descript2: "力F和力的作用时间t的乘积叫做冲量。 冲量是描述力的时间积累效应的物理量(过程量)",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "I=p, Ft=p动量定理",
print: "I=Δp, Ft=Δp ",
form_chn: "动量定理",
class1: "力学",
class2: "",
class3: "",
descript1: "Δp: 动量变化量<br>I: 冲量<br>F: 力<br>t: 力的作用时间",
descript2: "物体所受合外力的冲量，等于物体的动量变化量",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//角动量
{formula: "L=rp, L=rmv 角动量",
print: "L=r×p, L=r×mv",
form_chn: "角动量",
class1: "力学",
class2: "角动量",
class3: "",
descript1: "L:角动量<br>r:质点到轴心的距离<br>p:动量<br>m:质量<br>v:线速度",
descript2: "角动量的大小：L=rpsinθ，θ为r与p的夹角<br>角动量的方向：角动量是两个矢量的叉乘，遵循右手螺旋法则。右手四指指向矢径的方向，转过一个小于180度的角后指向动量的方向，则大拇指所指的方向为角动量的方向",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "M=dL/dt M=L/t角动量定理 动量矩定理",
print: "M=dL/dt ",
form_chn: "角动量定理",
class1: "力学",
class2: "角动量",
class3: "",
descript1: "M:力矩<br>L:角动量<br>t:时间",
descript2: "质点相对于某一点/轴的角动量对时间的导数，等于作用在质点上合外力的力矩",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//功和机械能
{formula: "W=Fs W=Fs cosθ机械功",
print: "W=F•s, W=Fs cosθ",
form_chn: "功",
class1: "力学",
class2: "功",
class3: "",
descript1: "W:功<br>F: 力<br>s: 距离<br>θ: 力方向与位移方向的夹角",
descript2: "功等于作用在物体上的力×物体在力的方向上移动的距离, 大小为W=Fs cosθ",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "P=W/t, P=Fv 功率",
print: "P=W/t, P=Fv",
form_chn: "功率",
class1: "力学",
class2: "功",
class3: "",
descript1: "P: 功率<br>W:功<br>t: 时间<br>F: 力<br>v: 速度",
descript2: "单位时间内所作的功等于功率",
photo: "",
apply: "", 
de: "P=W/t<br>W=Fs<br>P=F(s/t)=Fv",
eg_q: "",
eg_a: "",
},


{formula: "Ek=mv2/2 Ek=1/2mv Ek=(1/2)mv动能",
print: "Ek=mv²/2",
form_chn: "动能",
class1: "力学",
class2: "能量",
class3: "",
descript1: "E<sub>k</sub>:动能<br>m: 质量<br>v: 速度",
descript2: "动能的大小为物体质量与速度平方乘积的二分之一",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " W=Ek2-Ek1动能定理",
print: "W=E<sub>k2</sub>-E<sub>k1</sub> ",
form_chn: "动能定理",
class1: "力学",
class2: "能量",
class3: "",
descript1: "W:合外力对物体做的总功<br>Ek1:物体的初动能<br>Ek2:物体的末动能",
descript2: "合外力对物体所做的功等于物体动能的变化",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " Ep=mgh 重力势能",
print: "E<sub>p</sub>=mgh",
form_chn: "重力势能",
class1: "力学",
class2: "能量",
class3: "",
descript1: "Ep:重力势能<br>m:质量<br>g:重力加速度<br>h:高度",
descript2: "物体由于被举高而具有的能叫做重力势能, 大小与所选取的参考点有关",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "Ep=1/2kx2 Ep=(1/2)kx2弹性势能",
print: "E<sub>p</sub>=(1/2)kx²",
form_chn: "弹性势能",
class1: "力学",
class2: "能量",
class3: "",
descript1: "Ep:弹性势能<br>k:劲度系数<br>x:形变量",
descript2: "弹性势能：物体因为发生弹性形变而具有的能量",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//天体运动
{formula: "F=GMm/R2 万有引力定律",
print: "F=GMm/R²",
form_chn: "万有引力定律",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "F: 两个物体之间的引力<br>G:万有引力常量<br>M: 物体1的质量<br>m: 物体2的质量<br>r: 两个物体之间的距离",
descript2: "引力大小与它们质量的乘积成正比与它们距离的平方成反比",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " T2/a3=K T2/R3=K, T2/R3=4π2/GM 开普勒第三定律 天体运动",
print: "T<sup>2</sup>/a<sup>3</sup>=K, T<sup>2</sup>/a<sup>3</sup> = 4π<sup>2</sup>/ GM ",
form_chn: "开普勒第三定律",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "a:轨道半径/半长轴<br>T:周期<br>K:常量(与行星质量无关,取决于中心天体的质量)<br>G:万有引力常量<br>M:中心天体的质量",
descript2: "绕以中心天体为焦点的椭圆轨道运行的所有行星，其各自椭圆轨道半长轴的立方与周期的平方之比是一个常量",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "g=GM/R2 天体表面的重力加速度 天体运动",
print: "g=GM/R² ",
form_chn: "天体表面的重力加速度",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "g:重力加速度<br>R:天体半径<br>G:万有引力常量<br>M:中心天体的质量",
descript2: "",
photo: "",
apply: "", 
de: "GMm/R²=mg<br>g=GM/R² ",
eg_q: "",
eg_a: "",
},


{formula: " v=√(GM/r), v=√(gR) 第一宇宙速度 环绕速率 环绕速度 天体运动速度",
print: "v=√(GM/r), v=√(gR)",
form_chn: "第一宇宙速度, 环绕速度",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "v:环绕速度<br>r:轨道半径/半长轴<br>G:万有引力常量<br>M:中心天体的质量",
descript2: "物体在地面附近绕地球做匀速圆周运动的速度叫做第一宇宙速度v≈7.9km/s",
photo: "",
apply: "", 
de: "万有引力=向心力<br>GMm/r²=mv²/r<br>v²=GM/r",
eg_q: "",
eg_a: "",
},


{formula: "v=√(2GM/r)第二宇宙速度, 逃逸速度, 脱离速度 天体运动",
print: "v=√(2GM/r)",
form_chn: "第二宇宙速度, 逃逸速度",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "v:逃逸速度<br>r:轨道半径/半长轴<br>G:万有引力常量<br>M:中心天体的质量",
descript2: "地球的逃逸速度约11.2km/s",
photo: "",
apply: "", 
de: "距离地球无穷远时物体受到的引力势能为零<br>机械能守恒: <br>(1/2)mv²+(-GMm/r)=0<br>v²=2GM/r",
eg_q: "",
eg_a: "",
},


{formula: "Ep=-GMm/r 引力势能 天体运动",
print: "E<sub>p</sub>=-GMm/r",
form_chn: "引力势能",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "E<sub>p</sub>: 引力势能<br>r:距离<br>G: 引力常数<br>M, m:天体的质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "E=-GMm/2a 天体运动机械能 总机械能 天体运动能量 天体运动总能量",
print: "E=-GMm/2a",
form_chn: "天体运动机械能",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "E: 能量<br>a:半长轴/圆形轨道半径<br>G: 引力常数<br>M, m:天体的质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "v=√(2GM(1/r-1/2a ))椭圆轨道上任意处的速率 椭圆轨道速率 椭圆轨道速度天体运动",
print: "v=√(2GM (1/r - 1/2a)) ",
form_chn: "椭圆轨道上任意处的速率",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "v:速率<br>r:距离<br>a:半长轴<br>G: 引力常数<br>M:中心天体的质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "x2/a2+y2/b2=1, a=-GMm/2E, b=√(-L2/2mE) 天体运动椭圆轨道方程",
print: "x²/a²+y²/b² = 1, a = -GMm/2E, b = √(-L²/2mE) ",
form_chn: "椭圆轨道方程",
class1: "力学",
class2: "天体运动",
class3: "",
descript1: "a:半长轴<br>b:半短轴<br>E:机械能<br>L:角动量<br>G:万有引力常量<br>M:中心天体的质量<br>m:环绕天体的质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//振动与波
{formula: " X=Acos(wt+θ) 简谐振动方程 简谐振动位移 简谐运动方程 ",
print: "x=Acos(ωt+θ)",
form_chn: "简谐振动方程",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "x: 位移<br>A: 振幅<br>ω:角速度<br>t:时刻<br>θ: 初相位",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "v=-wAsin(wt+θ) 简谐振动的速度 简谐振动速度 简谐运动速度",
print: "v=-ωAsin(ωt+θ)",
form_chn: "简谐振动的速度",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "v: 线速度<br>A: 振幅<br>ω:角速度<br>t:时刻<br>θ: 初相位",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " a=-w2Acos(wt+θ) 简谐振动的加速度 简谐振动加速度 简谐运动加速度",
print: "a=-ω²Acos(ωt+θ) ",
form_chn: "简谐振动的加速度",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "a: 加速度<br>A: 振幅<br>ω:角速度<br>t:时刻<br>θ: 初相位",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "E=1/2kA2, E=1/2mw2A2 简谐振动能量",
print: "E=½kA², E=½mω²A²",
form_chn: "简谐振动能量",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "E:能量<br>k:振动系统的回复力系数<br>A: 振幅<br>ω:角速度<br>m:质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " T=2π√(m/k)简谐运动周期简谐振动周期",
print: "T=2π√(m/k) ",
form_chn: "简谐振动周期",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "T: 周期<br>m:质量<br>k:振动系统的回复力系数",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "T=2π√(L/g) 单摆周期",
print: "T=2π√(L/g) ",
form_chn: "单摆周期",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "T: 单摆周期<br>L:单摆的长度<br>g:重力加速度",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "v=λf 波速, 波长和频率",
print: "v=λf",
form_chn: "波速, 波长和频率",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "v:波速<br>λ:波长<br>f:频率",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "y=Acos(wt-2πxλ+φ) 平面简谐波的波动方程",
print: "y=Acos(ωt-2πxλ+φ)",
form_chn: "平面简谐波的波动方程",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "y:位移<br>x: 距波源的位移(自变量)<br>t:时刻(自变量)<br>A: 振幅<br>ω:角速度<br>λ:波长<br>φ: 初相位",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " f=f0(v+v0)/(v+vs) 多普勒效应",
print: "f=f<sub>0</sub>(v±v<sub>0</sub>)/(v-+v<sub>s</sub>)",
form_chn: "多普勒效应",
class1: "力学",
class2: "振动与波",
class3: "",
descript1: "f:观察到的频率<br>f<sub>0</sub>:原始发射频率<br>v:波在该介质中的行进速度<br>v<sub>0</sub>:观察者速度, 若接近发射源则+, 远离则-<br>v<sub>s</sub>:发射源速度，若接近观察者则-, 远离则+",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},













//热学
//热传递
{formula: "Q=K(T1-T2)St/L 热传递",
print: "Q=K(T<sub>1</sub>-T<sub>2</sub>)St/L ",
form_chn: "热传递",
class1: "热学",
class2: "热传递",
class3: "",
descript1: "K: 导热系数<br>L: 长度/厚度<br>S: 横截面积<br>t: 传热时间<br>T1, T2: 两个热源的温度",
descript2: "厚度为L截面面积为S的材料, 两侧热源温度分别为T<sub>1</sub>和T<sub>2</sub>, 在t时间内传递的热量为Q",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},

{formula: "J=σT4, J=εσT4 斯忒藩定律 黑体辐射",
print: "J=σT<sup>4</sup>, J=εσT<sup>4</sup>",
form_chn: "斯忒藩定律 黑体辐射",
class1: "热学",
class2: "热传递",
class3: "热辐射",
descript1: "ε: 表面辐射系数，ε=1时为绝对黑体(将辐射到它表面上的能量全部吸收)<br>σ: 斯忒藩常量σ ≈ 5.67×10<sup>-8</sup>W⋅m<sup>-2</sup>⋅K<sup>-4</sup><br>T: 黑体的温度(K)",
descript2: "黑体单位表面积的辐射功率为J=εσT<sup>4</sup>",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "Q=cm△t 吸热 放热",
print: "Q=cm△t ",
form_chn: "吸热 放热",
class1: "热学",
class2: "热传递",
class3: "",
descript1: "Q: 吸收或放出的热量<br>c: 物质的比热容<br>m: 物质的质量<br>△t: 温度的变化量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "温度为50℃，质量为8kg的一壶水，加热到100℃需要吸收多少热量？",
eg_a: "Q=cm△t <br>=4200×8×(100-50)<br>=1.68×10<sup>6</sup>J",
},

{formula: "Q=qm 燃料燃烧放热",
print: "Q=qm ",
form_chn: "燃料燃烧放热",
class1: "热学",
class2: "热传递",
class3: "",
descript1: "Q: 完全燃烧释放的热量<br>m: 燃料质量<br>q: 该物质的热值(J/kg)",
descript2: "质量m, 热值q的固体或液体燃料完全燃烧释放的热量为Q",
photo: "",
apply: "一般用于计算固体液体燃料的燃烧放热", 
de: "",
eg_q: "",
eg_a: "",
},

{formula: "Q=Vq 气体燃料燃烧放热",
print: "Q=Vq",
form_chn: "气体燃料燃烧放热",
class1: "热学",
class2: "热传递",
class3: "",
descript1: "Q: 完全燃烧释放的热量<br>V: 燃料体积<br>q: 该物质的热值(J/m<sup>3</sup>)",
descript2: "体积V, 热值q的气体燃料完全燃烧释放的热量为Q",
photo: "",
apply: "气体燃料燃烧放热", 
de: "",
eg_q: "",
eg_a: "",
},


//热力学第一定律
{formula: "E=(i/2)nRT , E=(i/2)NkT 内能",
print: "E=(i/2)nRT , E=(i/2)NkT ",
form_chn: "内能",
class1: "热学",
class2: "",
class3: "",
descript1: "n: 物质的量<br>R: 摩尔气体常量R≈8.31J/(mol⋅K)<br>T: 温度(K)<br>N: 粒子数<br> k: 玻尔兹曼常数 k=R/N<sub>A</sub>≈1.38×10<sup>-23</sup>J/K <br>i: 自由度(单原子i=3, 双原子i=5, 多原子i=6)",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "△E=W+Q热力学第一定律" ,
print: "△E=W+Q ",
form_chn: "热力学第一定律",
class1: "热学",
class2: "热力学第一定律",
class3: "",
descript1: "△E: 内能变化量<br>W: 外界对系统所做的功<br>Q: 吸收的热量",
descript2: "系统内能变化量等于外界对系统所做的功加上吸收的热量<br>热力学第一定律本质上与能量守恒定律是的等同",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "W=0, △E=Q=nCv△T等容过程",
print: "W=0, △E=Q=nC<sub>v</sub>△T ",
form_chn: "等容过程",
class1: "热学",
class2: "热力学第一定律",
class3: "热力学过程",
descript1: "定容摩尔热容C<sub>v</sub>=iR/2",
descript2: "等容过程中对外不做功",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "W=-p△V, △E=(i/2)nR△T, Q=nCp△T等压过程",
print: "W=-p△V, △E=(i/2)nR△T, Q=nC<sub>p</sub>△T ",
form_chn: "等压过程",
class1: "热学",
class2: "热力学第一定律",
class3: "热力学过程",
descript1: "W: 外界对系统所做的功<br> C<sub>p</sub>: 定压摩尔热容C<sub>p</sub>=(i+2)/2",
descript2: "",
photo: "",
apply: "", 
de: " C<sub>p</sub>=(i+2)/2:<br><br>Q=△E-W<br> Q=(i/2)nR△T + p△V <br> Q=(i/2)nR△T + nR△T <br> Q=[(i+2)/2]nR△T ",
eg_q: "",
eg_a: "",
},


{formula: "△E=0, W=-Q=-nRTln(V2/V1) 等温过程",
print: "△E=0, W=-Q=-nRT<i>ln</i>(V<sub>2</sub>/V<sub>1</sub>)",
form_chn: "等温过程",
class1: "热学",
class2: "热力学第一定律",
class3: "热力学过程",
descript1: " W: 外界对系统所做的功<br>V<sub>1</sub>:初始体积<br> V<sub>2</sub>:最终体积",
descript2: "等温过程中内能不变",
photo: "",
apply: "", 
de: "W=-∫p•dV<br>=-∫nRT•(dV/V)<br>=-nRT(<i>ln</i> V<sub>2</sub>-<i>ln</i> V<sub>1</sub>)<br>= -nRT<i>ln</i>(V<sub>2</sub>/V<sub>1</sub>)",
eg_q: "",
eg_a: "",
},

{formula: "Q=0, pVk=c, TVk-1=c 绝热过程",
print: "Q=0, pV<sup>k</sup>=常数, TV<sup>k-1</sup>=常数",
form_chn: "绝热过程",
class1: "热学",
class2: "热力学第一定律",
class3: "热力学过程",
descript1: "k: 绝热指数 k= C<sub>p</sub>/ C<sub>v</sub>=(i+2)/i",
descript2: "绝热过程中系统与外界没有热量交换, Q=0",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//热机
{formula: "η=W/Q1, η=1-Q2/Q1 热机效率",
print: "η=W/Q<sub>1</sub>, η=1-Q<sub>2</sub>/Q<sub>1</sub>",
form_chn: "热机效率",
class1: "热学",
class2: "热机",
class3: "",
descript1: "W:热机做的功<br>Q<sub>1</sub>:吸收的热量<br>Q<sub>2</sub>:放出(浪费)的热量",
descript2: "热机效率等于热机输出的功除以输入的热量",
photo: "",
apply: "", 
de: "",
eg_q: "一个热机在单个循环中总共做了300J的功，但浪费了900J 的能量。它的效率是多少？",
eg_a: "300/(300+900)=0.25",
},

{formula: "ω=Q/W 制冷系数",
print: "ω=Q/W ",
form_chn: "制冷系数",
class1: "热学",
class2: "热机",
class3: "",
descript1: "ω:制冷系数<br>Q: 吸热<br>W: 消耗外功",
descript2: "制冷系数为吸热量与消耗外功之比, 可大于1",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},

{formula: "η=1-T2/T1 卡诺循环 热机效率",
print: "η= 1-T<sub>2</sub>/ T<sub>1</sub>",
form_chn: "卡诺循环 热机效率",
class1: "热学",
class2: "热机",
class3: "",
descript1: " T<sub>1</sub>: 高温热源温度(K)<br>T<sub>2</sub>: 低温热源温度(K)",
descript2: "",
photo: "",
apply: "卡诺循环：理想的可逆循环，每个过程都是平衡过程", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "ω=T2/(T1-T2) 卡诺循环 制冷系数",
print: "ω= T<sub>2</sub>/(T<sub>1</sub>-T<sub>2</sub>)",
form_chn: "卡诺循环 制冷系数",
class1: "热学",
class2: "热机",
class3: "",
descript1: " T<sub>1</sub>: 高温热源温度(K)<br>T<sub>2</sub>: 低温热源温度(K)",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//热容和比热容
{formula: "C=Q/ΔT 热容",
print: "C=Q/ΔT ",
form_chn: "热容",
class1: "热学",
class2: "热容和比热容",
class3: "",
descript1: " C: 热容<br>Q: 吸热/放热量<br>ΔT: 因吸热/放热而产生的温度变化",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "c=C/m , c=Q/(m⋅ΔT )比热容",
print: "c=C/m , c=Q/(m⋅ΔT )",
form_chn: "比热容",
class1: "热学",
class2: "热容和比热容",
class3: "",
descript1: "C: 热容<br>m: 质量<br>Q: 吸收/放出的热量<br>ΔT: 因吸热/放热而产生的温度变化量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "cn=C/n 摩尔热容",
print: "c<sub>n</sub>= C/n ",
form_chn: "摩尔热容",
class1: "热学",
class2: "热容和比热容",
class3: "",
descript1: " C: 热容<br>n: 物质的量(mol)",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//理想气体 分子动理论
{formula: "pV=nRT (pV=NkT)理想气体状态方程",
print: "pV=nRT (pV=NkT)",
form_chn: "理想气体状态方程",
class1: "热学",
class2: "理想气体",
class3: "",
descript1: "p: 气压<br>V: 体积<br>n: 物质的量<br>R: 摩尔气体常量R≈8.31J/(mol⋅K) <br>T: 温度(K)<br>N: 粒子数<br> k: 玻尔兹曼常数 k=R/N<sub>A</sub>≈1.38×10<sup>-23</sup>J/K ",
descript2: "",
photo: "",
apply: "理想气体：理想气体的分子是质点，与其他分子无相互作用", 
de: "pV=nRT=NkT:<br> <br>pV<br>= nRT <br>=(M/μ) N<sub>A</sub> (R/N<sub>A</sub>) T<br>= NkT ",
eg_q: "",
eg_a: "",
},


{formula: "v=√(8kT/πm), v=√(8RT/πμ)气体分子 平均速率",
print: "v=√(8kT/πm), v=√(8RT/πμ)",
form_chn: "气体分子 平均速率",
class1: "热学",
class2: "理想气体",
class3: "",
descript1: "v: 平均速率<br>m: 一个分子的质量<br>μ: 摩尔质量<br>R: 摩尔气体常量R≈8.31J/(mol⋅K)<br>k: 玻尔兹曼常数 k=R/N<sub>A</sub>≈1.38×10<sup>-23</sup>J/K <br>T: 温度(K)",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "v=√(2kT/m), v=√(2RT/μ)最概然速率 最可几速率",
print: "v=√(2kT/m), v=√(2RT/μ)",
form_chn: "最概然速率 最可几速率",
class1: "热学",
class2: "理想气体",
class3: "",
descript1: "v: 最概然速率/最可几速率<br>m: 一个分子的质量<br>μ: 摩尔质量<br>R: 摩尔气体常量R≈8.31J/(mol⋅K)<br>k: 玻尔兹曼常数 k=R/N<sub>A</sub>≈1.38×10<sup>-23</sup>J/K <br>T: 温度(K)",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "vrms=√(3kT/m), vrms=√(3RT/μ)方均根速率",
print: "v<sub>rms</sub>=√(3kT/m), v<sub>rms</sub>=√(3RT/μ)",
form_chn: "方均根速率",
class1: "热学",
class2: "理想气体",
class3: "",
descript1: "v<sub>rms</sub>: 方均根速率<br>m: 一个分子的质量<br>μ: 摩尔质量<br>R: 摩尔气体常量R≈8.31J/(mol⋅K)<br>k: 玻尔兹曼常数 k=R/N<sub>A</sub>≈1.38×10<sup>-23</sup>J/K <br>T: 温度(K)",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "Ek=3/2kT 理想气体气体分子的平均动能",
print: " E<sub>k</sub>=(3/2)kT ",
form_chn: "理想气体气体分子的平均动能",
class1: "热学",
class2: "理想气体",
class3: "",
descript1: "E<sub>k</sub>:平均(平动)动能<br>k: 玻尔兹曼常数 k=R/N<sub>A</sub>≈1.38×10<sup>-23</sup>J/K<br>T: 温度(K)",
descript2: "对于单原子理想气体,内能=平均动能",
photo: "",
apply: "", 
de: "设气体分子速度为v，共有N个分子处于容积为V的容器中，容器x方向长度为a<br><br>先对一个分子x方向的运动进行研究:<br>每次撞击容器壁的冲量:<br>△p=2mv<sub>x</sub><br>每撞击一次的时间间隔<br>2a/ v<sub>x</sub><br>t时间内撞击次数<br>n=v<sub>x</sub>t/2a<br>由速度的矢量合成<br>v<sup>2</sup>= v<sub>x</sub><sup>2</sup>+ v<sub>y</sub><sup>2</sup>+ v<sub>z</sub><sup>2</sup><br>v<sub>x</sub><sup>2</sup>=(1/3) v<sup>2</sup><br> t时间内这个气体分子对该容器壁的总冲量<br>n⋅△p =2mv<sub>x</sub><sup>2</sup>t/2a= mv<sub>x</sub><sup>2</sup>t/a= mv<sup>2</sup>t/3a<br>t时间内所有气体分子对该容器壁的总冲量<br>I=N⋅n⋅△p=Nmv<sup>2</sup>t/3a<br>可得出压强<br>P=F/S<br>=I/St<br>=Nmv<sup>2</sup>t/3(abc)t<br>=Nmv<sup>2</sup>/3V<br>将P代入理想气体状态方程<br>PV=NkT<br>E<sub>k</sub>=mv<sup>2</sup>/2=(3/2)kT ",
eg_q: "",
eg_a: "",
},


{formula: "p=Nmv2/3V 理想气体压强公式",
print: " p=Nmv<sup>2</sup>/3V ",
form_chn: "理想气体压强公式",
class1: "热学",
class2: "理想气体",
class3: "",
descript1: " N:分子数<br>m:分子的质量<br>v: 分子速率(方均根速率)<br>V: 体积",
descript2: "",
photo: "",
apply: "", 
de: "设气体分子速度为v，共有N个分子处于容积为V的容器中，容器x方向长度为a<br><br>先对一个分子x方向的运动进行研究:<br>每次撞击容器壁的冲量:<br>△p=2mv<sub>x</sub><br>每撞击一次的时间间隔<br>2a/ v<sub>x</sub><br>t时间内撞击次数<br>n=v<sub>x</sub>t/2a<br>由速度的矢量合成<br>v<sup>2</sup>= v<sub>x</sub><sup>2</sup>+ v<sub>y</sub><sup>2</sup>+ v<sub>z</sub><sup>2</sup><br>v<sub>x</sub><sup>2</sup>=(1/3) v<sup>2</sup><br> t时间内这个气体分子对该容器壁的总冲量<br>n⋅△p =2mv<sub>x</sub><sup>2</sup>t/2a= mv<sub>x</sub><sup>2</sup>t/a= mv<sup>2</sup>t/3a<br>t时间内所有气体分子对该容器壁的总冲量<br>I=N⋅n⋅△p=Nmv<sup>2</sup>t/3a<br>可得出压强<br>P=F/S<br>=I/St<br>=Nmv<sup>2</sup>t/3(abc)t<br>=Nmv<sup>2</sup>/3V<br>",
eg_q: "",
eg_a: "",
},


//物态
{formula: "Q=Lm 气液相变 汽化热",
print: "Q=Lm ",
form_chn: "气液相变 汽化热",
class1: "热学",
class2: "物态变化",
class3: "",
descript1: "L: 汽化热/汽化潜热<br>Q: 热量<br>m: 质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "Q=λm 固液相变 熔化热",
print: "Q=λm ",
form_chn: "固液相变 熔化热",
class1: "热学",
class2: "物态变化",
class3: "",
descript1: " λ: 熔化热<br>Q: 热量<br>m: 质量",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},




//电磁学
//静电场
{formula: "F=kQq/r2, F=Qq/4πε0r2 库仑定律",
print: "F=kQq/r<sup>2</sup>, F=Qq/4πε<sub>0</sub>r<sup>2</sup>",
form_chn: "库仑定律",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "F:力<br>k:静电力常量<br>ε<sub>0</sub>:真空介电常数<br>Q,q:点电荷电荷量<br>r:距离",
descript2: "真空中两个静止的点电荷之间的相互作用力同它们的电荷量的乘积成正比,与它们的距离的二次方成反比",
photo: "",
apply: "只适用于点电荷之间", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "E=F/q电场强度 场强定义式",
print: "E=F/q",
form_chn: "电场强度",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "E:场强<br>F:力<br>q:电荷量",
descript2: "电场强弱为试探电荷所受的力与试探点电荷带电量的比值，方向为试探点电荷(正电荷)在该点所受电场力的方向",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " E=kq/r2, E=q/4πε0r2点电荷的场强",
print: "E=kq/r<sup>2</sup>, E=q/4πε<sub>0</sub>r<sup>2</sup>",
form_chn: "点电荷的场强",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "E:场强<br>k:静电力常量<br>ε<sub>0</sub>:真空介电常数<br>q:点电荷电荷量<br>r:距离",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "Φ=E∙S, Φ=EScosθ电通量",
print: "Φ=E∙S, Φ=EScosθ",
form_chn: "电通量",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "E: 电场强度<br>S:面积<br>θ:电场强度矢量与面法向的夹角",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "E∙S=(1/ε0)∑q 静电场的高斯定理 高斯通量理论",
print: "E∙S=(1/ε<sub>0</sub>)∑q",
form_chn: "高斯定理",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "E: 电场强度<br>S:面积<br>ε<sub>0</sub>:真空介电常数<br>q:(闭合曲面内的)点电荷电荷量",
descript2: "电场通过任何闭合曲面的电通量正比于该闭合曲面内的电量代数和",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "∮E∙dL=0, 静电场环路定理",
print: "∮E∙dL=0",
form_chn: "静电场环路定理",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "∮E∙dL: 静电场的环量",
descript2: "在静电场中,场强沿任意闭合路径的线积分等于(环量为0)",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "U=Ep/q 电势",
print: "U=Ep/q",
form_chn: "电势",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "U:电势<br>Ep:电势能<br>q:电荷量",
descript2: "电势能跟它所带的电荷量（有正负）之比为电势",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "U=Ed , U=EdL电势差",
print: "U=E∙d, U=∫E∙dL",
form_chn: "电势差",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "U:电势<br>E: 电场强度<br>d: 距离",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " U=kQ/r, U=Q/4πε0r点电荷的电势 点电荷电势",
print: "U=kQ/r<sup>2</sup>, U=Q/4πε<sub>0</sub>r ",
form_chn: "点电荷的电势",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "U:电势<br>k:静电力常量<br>ε<sub>0</sub>:真空介电常数<br>Q:点电荷电荷量<br>r:距离",
descript2: "",
photo: "",
apply: "", 
de: "U=∫E∙dr<br>=∫(kq/r<sup>2</sup>)∙dr<br>=kq/r",
eg_q: "",
eg_a: "",
},


{formula: "Ep=kQq/r, U=Qq/4πε0r点电荷的电势能 点电荷电势能",
print: "Ep =kQq/r<sup>2</sup>, Ep =Qq/4πε<sub>0</sub>r",
form_chn: "点电荷的电势能",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "Ep:电势能<br>k:静电力常量<br>ε<sub>0</sub>:真空介电常数<br>Q,q:点电荷电荷量<br>r:距离",
descript2: "",
photo: "",
apply: "", 
de: "Ep<br>=∫F∙dr<br>=∫(kQq/r<sup>2</sup>)∙dr<br>=kQq/r ",
eg_q: "",
eg_a: "",
},


{formula: " E=σ/2ε0 均匀带电无限大平板电场强度 均匀带电无限大平板的电场强度",
print: "E=σ/2ε<sub>0</sub> ",
form_chn: "均匀带电无限大平板的电场强度",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "σ:电荷面密度Q/S<br>ε<sub>0</sub>:真空介电常数",
descript2: "",
photo: "",
apply: "", 
de: "用高斯定理:<br>E∙2S=Q/ε<sub>0</sub><br>Q=σS<br>所以E=σ/2ε<sub>0</sub> ",
eg_q: "",
eg_a: "",
},


{formula: " E=σ/ε0均匀带电无限大平行板间电场强度, 均匀带电无限大平行板的电场强度",
print: "E=σ/ε<sub>0</sub> ",
form_chn: "带电无限大平行板间电场强度",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "σ:电荷面密度Q/S<br>ε<sub>0</sub>:真空介电常数",
descript2: "",
photo: "",
apply: "", 
de: "对于一块带电平板:<br>高斯定理:E∙2S=Q/ε<sub>0</sub><br>且Q=σS<br>所以E=σ/2ε<sub>0</sub><br>两块平行放置的带电板E=σ/ε<sub>0</sub> ",
eg_q: "",
eg_a: "",
},


{formula: " We=(1/2)εoεrE2 电场能量密度",
print: "w<sub>e</sub>=(1/2) ε<sub>0</sub> ε<sub>r</sub> E<sup>2</sup>",
form_chn: "电场能量密度",
class1: "电磁学",
class2: "静电场",
class3: "",
descript1: "w<sub>e</sub>:电场能量密度<br>ε<sub>0</sub>: 真空介电常数<br>ε<sub>r</sub>: 相对介电常数<br>E:电场强度",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//电介质
{formula: "ε=εrε0, e=ere0, 介电常数 相对介电常数",
print: "ε=ε<sub>r</sub>∙ε<sub>0</sub>",
form_chn: "介电常数",
class1: "电磁学",
class2: "静电场",
class3: "电介质",
descript1: "ε:介电常数<br>ε<sub>r</sub>:相对介电常数<br>ε<sub>0</sub>:真空介电常数",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "εr=C/C0, εr=E0/E相对介电常数",
print: "ε<sub>r</sub>=C/C<sub>0</sub>, ε<sub>r</sub>=E<sub>0</sub>/E ",
form_chn: "相对介电常数",
class1: "电磁学",
class2: "静电场",
class3: "电介质",
descript1: "εr:相对介电常数<br>C<sub>0</sub>:真空中电容<br>C:加入介质后的电容<br>E<sub>0</sub>: 真空中的场强<br>E:充满电介质后的场强",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//电容
{formula: "C=Q/U, Q=CU, U=Q/C电容定义式",
print: "C=Q/U (Q=CU, U=Q/C)",
form_chn: "电容定义式",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "C:电容,单位为法拉(F)<br>Q:电荷量< br>U:电压",
descript2: "电容器的电容C等于所带电荷Q与电势差U的比值",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " C=C1+C2 电容器的并联",
print: "C=∑C<sub>i</sub>, C=C<sub>1</sub>+ C<sub>2</sub>+...",
form_chn: "电容器的并联",
class1: "电磁学",
class2: "",
class3: "",
descript1: "C:总电容",
descript2: "并联：将多个电容器的正极连起来，负极连起来",
photo: "",
apply: "", 
de: "并联时电势差相等，总电荷量等于各个电容器的电量之和<br>Q=Q1+Q2+...<br>CU=C1U+C2U+...<br>C=C1+C2+...",
eg_q: "",
eg_a: "",
},


{formula: "1/C=1/C1+1/C2电容器的串联",
print: "1/C=∑C<sub>i</sub><sup>-1</sup>,1/C=1/C<sub>1</sub>+ 1/C<sub>2</sub>+...",
form_chn: "电容器的串联",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "C:总电容",
descript2: "串联：将前一个电容器的负极与后一个的正极相连",
photo: "",
apply: "", 
de: "串联时总电压等于各个电容器的电压之和, 带电量相等<br>U=U1+U2+...<br>Q/C=Q/C1+Q/C2+...<br>1/C=1/C1+1/C2+...",
eg_q: "",
eg_a: "",
},


{formula: " W=Q2/2C, W=CU2/2, W=QU/2电容器储存的能量 电容能量 电容器能量 电容器静电能",
print: "W=Q<sup>2</sup>/2C, W=CU<sup>2</sup>/2, W=QU/2",
form_chn: "电容器储存的能量",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "W: 电容器储存的能量<br>C: 电容<br>Q: 电荷量< br>U: 电压",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "C=εS/d, C=εrS/4πkd平行板电容器的电容 平行板电容器电容",
print: "C=εS/d, C=ε<sub>r</sub>S/4πkd",
form_chn: "平行板电容器电容",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "S: 面积<br>d: 板间距<br>ε: 介电常数<br>ε<sub>r</sub>: 相对介电常数<br>k: 静电力常量",
descript2: "",
photo: "",
apply: "", 
de: "真空中平行板间电场强度为E<sub>0</sub>=σ/ε<sub>0</sub>=Q/ε<sub>0</sub>S<br>加入电介质后平行板间电场强度为E=E<sub>0</sub>/ε<sub>r</sub>=Q/εS<br>电势差为U=Ed=Qd/εS<br>电容为C=Q/U=εS/d ",
eg_q: "",
eg_a: "",
},


{formula: "C=4πεR 孤立导体球的电容",
print: "C=4πεR",
form_chn: "孤立导体球的电容",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "R: 半径<br>ε: 介电常数",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "C=2πεH/ln(R2/R1) 同轴圆柱形电容器的电容",
print: "C=2πεH/ln(R<sub>2</sub>/R<sub>1</sub> ",
form_chn: "同轴圆柱形电容器的电容",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "H: 圆柱高<br>ε: 介电常数<br>R<sub>1</sub>,R<sub>2</sub>: 内外半径",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "C=4πεR1R2/(R2-R1) 同心球形电容器的电容",
print: "C=4πεR<sub>1</sub> R<sub>2</sub>/( R<sub>2</sub>- R<sub>1</sub>)",
form_chn: "同心球形电容器的电容",
class1: "电磁学",
class2: "静电场",
class3: "电容",
descript1: "ε: 介电常数<br>R<sub>1</sub>,R<sub>2</sub>: 内外半径",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},



//电路
{formula: "I=Q/t I=dQ/dt电流定义式",
print: "I=Q/t, I=dQ/dt",
form_chn: "电流定义式",
class1: "电磁学",
class2: "电流",
class3: "",
descript1: "I:电流<br>Q:电荷<br>t:时间",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "R=ρL/S, R=pL/S 电阻定律",
print: "R=ρL/S",
form_chn: "电阻定律",
class1: "电磁学",
class2: "电阻",
class3: "",
descript1: "R:电阻<br>ρ:电阻率<br>L:长度<br>S:横截面积",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "R=R1+R2+… 电阻串联",
print: "R=R1+R2+…",
form_chn: "电阻串联",
class1: "电磁学",
class2: "电阻",
class3: "",
descript1: "R:总电阻",
descript2: "",
photo: "",
apply: "", 
de: " I=I1=I2…<br>U=U1+U2+…<br>IR=I1R1+I2R2+…<br>R=R1+R2+…",
eg_q: "",
eg_a: "",
},


{formula: "1/R=1/R1+1/R2+… 电阻并联",
print: "1/R=1/R1+1/R2+…",
form_chn: "电阻并联",
class1: "电磁学",
class2: "电阻",
class3: "",
descript1: "R:总电阻",
descript2: "",
photo: "",
apply: "", 
de: "U=U1=U2=…<br>I=I1+I2+…<br>U/R=U1/R1+U2/R2+...<br>1/R=1/R1+1/R2+…",
eg_q: "",
eg_a: "",
},


{formula: "I=U/R  (U=IR, R= U/I) 欧姆定律(部分电路) ",
print: "I=U/R (U=IR, R= U/I)",
form_chn: "欧姆定律(部分电路) ",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "I:电流, 单位:安培A<br>U:电压, 单位:伏特V<br>R:电阻, 单位:欧姆Ω",
descript2: "通过某一导体的电流与这段导体两端的电压成正比，与这段导体的电阻成反比",
photo: "",
apply: "", 
de: "欧姆定律适用于纯电阻电路，金属导电和电解液导电<br>理想电源，内阻为0",
eg_q: "",
eg_a: "",
},



{formula: " I=E/(R+r), E=I (R+r) 全电路欧姆定律 闭合电路欧姆定律",
print: "I=E/(R+r) ",
form_chn: "闭合电路欧姆定律",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "I:电路中电流<br>E:电动势<br>R:外总电阻<br>r:电池内阻",
descript2: "闭合电路的电流跟电源的电动势成正比，跟内外电路的电阻之和成反比",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "U=E-Ir 路端电压",
print: "U=E-Ir",
form_chn: "路端电压",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "U:路端电压(电压表接在电源两极间测得的电压)<br>I:电路中电流<br>E:电动势<br>r:电池内阻",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "P=W/t, P=UI, P=U2/R, P=I2R 电功率",
print: "P=W/t, P=UI ( P= U<sup>2</sup>/R, P= I<sup>2</sup>R )",
form_chn: "电功率",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "P:电功率(瓦特W)<br>U:电压<br>I:电流<br>R:电阻<br>t:时间<br>W:电功",
descript2: "电流在单位时间内做的功叫做电功率, 用来表示消耗电能的快慢<br>每个用电器都有一个正常工作的电压值叫额定电压，用电器在额定电压下正常工作的功率叫做额定功率，用电器在实际电压下工作的功率叫做实际功率",
photo: "",
apply: "P=UI无条件<br>P=I<sup>2</sup>R 纯电阻电路<br>P=U<sup>2</sup>/R 纯电阻电路", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "W=Pt W=UIt W=I2Rt  W=(U2/R)t W=U2t/R 电功",
print: "W=Pt, W=UIt ( W=I<sup>2</sup>Rt, W=U<sup>2</sup>t/R )",
form_chn: "电功",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "W:电功<br>U:电压<br>I:电流<br>R:电阻<br>t:时间<br>P:电功率",
descript2: "",
photo: "",
apply: "W=UIt 无条件<br>W=I<sup>2</sup>Rt 纯电阻电路<br>W=(U<sup>2</sup>/R)t 纯电阻电路", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "Q=Pt Q=UIt Q=I2Rt  Q=(U2/R)t电热 焦耳定律",
print: "Q=I<sup>2</sup>Rt ( Q=UIt, Q=U<sup>2</sup>t/R )",
form_chn: "焦耳定律",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "Q:电热<br>U:电压<br>I:电流<br>R:电阻<br>t:时间",
descript2: "",
photo: "",
apply: "Q=I<sup>2</sup>Rt所有电路<br>Q=W=Pt,  Q=UIt, Q=U<sup>2</sup>t/R纯电阻电路", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "R=(n-1)Rg 电压表改装 电表改装",
print: "R=(n-1)R<sub>g</sub> ",
form_chn: "电压表改装",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "R:分压电阻n:量程扩大倍数 Rg:原电表内阻",
descript2: "",
photo: "dianyabiao.png",
apply: "改装后量程V为原来量程Vg的n倍<br>V=nV<sub>g</sub><br>I<sub>g</sub> (R<sub>g</sub>+R)=n I<sub>g</sub>R<sub>g</sub> <br>R=(n-1)R<sub>g</sub>", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " R=Rg/(n-1) 电流表改装 电表改装",
print: "R=R<sub>g</sub>/(n-1)",
form_chn: "电流表改装",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "R:分流电阻n:量程扩大倍数 Rg:原电表内阻",
descript2: "",
photo: "dianliubiao.png",
apply: "", 
de: "改装后量程I为原来量程I<sub>g</sub>的n倍<br>I=n I<sub>g</sub> <br>I=I<sub>g</sub>+I<sub>R</sub><br>nI<sub>g</sub>=I<sub>g</sub>+I<sub>R</sub><br>nV/R<sub>g</sub>=V/R<sub>g</sub>+V/R<br>n=1+R<sub>g</sub>/R<br>=R<sub>g</sub>/(n-1)",
eg_q: "",
eg_a: "",
},


{formula: "基尔霍夫方程组 基尔霍夫定律",
print: "∑I = 0, ∑IR = ∑ε",
form_chn: "基尔霍夫方程组",
class1: "电磁学",
class2: "电路",
class3: "",
descript1: "",
descript2: "基尔霍夫第一方程组: 流入与流出节点电流的代数和为零<br>基尔霍夫第二方程组: 沿回路环绕一周，电势降落的代数和为零",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//光学
//几何光学
{formula: "i=r, θi=θr反射定律",
print: "θ<sub>i</sub>=θ<sub>r</sub> ",
form_chn: "反射定律",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "θ<sub>i</sub>: 入射角<br>θ<sub>r</sub>: 反射角",
descript2: "光反射时，反射角等于入射角<br>反射光线、入射光线、法线都在同一平面内<br>反射光线、入射光线分居法线两侧",
photo: "fanshedinglv.png",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "n1sini1=n2sini2斯涅尔定律 折射定律",
print: "n<sub>1</sub>sin i<sub>1</sub>=n<sub>2</sub>sin i<sub>2</sub>",
form_chn: "斯涅尔定律",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: " n<sub>1</sub>, n<sub>2</sub>: 两种介质的折射率<br>i<sub>1</sub>, i<sub>2</sub>: 入射角和反射角",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "n=c/v绝对折射率",
print: "n=c/v",
form_chn: "绝对折射率",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "n: 介质的(绝对)折射率<br>c: 光在真空中的速度，约3×10<sup>8</sup>m/s <br>v: 光在该介质中的速度",
descript2: "绝对折射率等于真空中光速与介质中光速之比<br>常用的数值: n空气=1, n水=4/3, n玻璃=1.5",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "n1sinic=n2临界角, 全反射",
print: "n<sub>1</sub>sin i<sub>c</sub>=n<sub>2</sub>",
form_chn: "临界角, 全反射",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "i<sub>c</sub>: 临界角<br>n<sub>1</sub>:光密介质折射率<br>n<sub>2</sub>: 光疏介质折射率<br> n<sub>1</sub>大于 n<sub>2</sub>",
descript2: "发生全反射时光从光密介质进入光疏介质且入射角大于等于临界角",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "1/s+1/s'=1/f 1/v+1/u=1/f  凸透镜成像公式 高斯公式",
print: "1/s+1/s'=1/f ",
form_chn: "高斯公式",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "s:物距<br>s':像距<br>f:焦距",
descript2: "物距的倒数与像距的倒数之和等于焦距的倒数",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "1/s+1/s'=2/r单球面反射成像公式",
print: "1/s+1/s'=2/r ",
form_chn: "单球面反射成像公式",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "s: 物距(实物s>0, 虚物s<0)<br>s':像距(实像s'>0, 虚像s'<0)<br>r: 曲率半径(凹面镜r>0, 凸面镜r<0)",
descript2: "球面镜物方焦距与像方焦距重合, f=r/2",
photo: "",
apply: "满足光的直进，不考虑衍射<br>傍轴条件：发出的光线与主光轴夹角很小", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "m=-s'/s单球面反射成像 横向放大率",
print: "m=-s'/s",
form_chn: "单球面反射成像 横向放大率",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "m:横向放大率<br>s:物距<br>s':像距",
descript2: "",
photo: "",
apply: "满足光的直进，不考虑衍射<br>傍轴条件：发出的光线与主光轴夹角很小", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "n1/s+n2/s'=(n1-n2)/r n1/s+n2/s'=(n2-n1)/r 单球面折射成像公式",
print: "n<sub>1</sub>/s+n<sub>2</sub>/s'=(n<sub>1</sub>-n<sub>2</sub>)/r",
form_chn: "单球面折射成像公式",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "s: 物距(实物s>0, 虚物s<0)<br>s':像距(实像s'>0, 虚像s'<0)<br>r: 曲率半径(凹面迎光r>0, 凸面迎光r<0)<br>n<sub>1</sub>: 左侧介质折射率(默认光从左侧射入)<br>n<sub>2</sub>: 右侧介质折射率",
descript2: "",
photo: "",
apply: "满足光的直进，不考虑衍射<br>傍轴条件：发出的光线与主光轴夹角很小", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "m=-n1s'/n2s单球面折射成像 横向放大率",
print: "m=-n<sub>1</sub>s'/n<sub>2</sub>s ",
form_chn: "单球面折射成像 横向放大率",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "m:横向放大率<br>s:物距<br>s':像距<br>n<sub>1</sub>: 左侧介质折射率(默认光从左侧射入)<br>n<sub>2</sub>: 右侧介质折射率",
descript2: "",
photo: "",
apply: "满足光的直进，不考虑衍射<br>傍轴条件：发出的光线与主光轴夹角很小", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: " 1/s+1/s'=((n-n')/n) (1/r1 -1/r2 ) 薄透镜成像, 双球面成像",
print: "1/s+1/s'=((n-n')/n) (1/r<sub>2</sub> -1/r<sub>1</sub>) ",
form_chn: "薄透镜成像",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "默认光从左侧射入<br>s: 物距(实物s>0, 虚物s<0)<br>s':像距(实像s'>0, 虚像s'<0)<br>r<sub>1</sub>, r<sub>2</sub>: 透镜左侧右侧曲率半径(凹面迎光r>0, 凸面迎光r<0)<br>n':透镜外侧介质折射率<br>n: 透镜折射率",
descript2: "",
photo: "",
apply: "薄透镜: 厚度远小于曲率半径<br>满足光的直进，不考虑衍射<br>傍轴条件：发出的光线与主光轴夹角很小", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "m=-s'/s薄透镜成像 双球面成像 横向放大率",
print: "m=-s'/s",
form_chn: "薄透镜成像 横向放大率",
class1: "光学",
class2: "几何光学",
class3: "",
descript1: "m:横向放大率<br>s:物距<br>s':像距",
descript2: "",
photo: "",
apply: "薄透镜: 厚度远小于曲率半径<br>满足光的直进，不考虑衍射<br>傍轴条件：发出的光线与主光轴夹角很小", 
de: "",
eg_q: "",
eg_a: "",
},


//波动光学
{formula: "δ=nl 光程",
print: "δ=nl",
form_chn: "光程",
class1: "光学",
class2: "波动光学",
class3: "",
descript1: "δ:光程<br>n:折射率<br>l:传播路程",
descript2: "光在介质中传播的路程折合为在相同时间内光线在真空中传播的距离",
photo: "",
apply: "", 
de: "n=c/v<br>δ=ct=nvt=nl",
eg_q: "",
eg_a: "",
},


{formula: "∆X=λD/d 杨氏双逢干涉 条纹间距",
print: "∆X=λD/d",
form_chn: "杨氏双逢干涉",
class1: "光学",
class2: "波动光学",
class3: "",
descript1: "∆X: 条纹间距<br>d:两条缝的距离<br>D:缝离屏幕的距离",
descript2: "",
photo: "",
apply: "缝离屏幕的距离D远大于两条缝的间距d<br>光干涉的条件: 频率同, 相位差恒定, 振动方向相同", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "r=kRλ 等厚干涉 牛顿环",
print: "r=√(kRλ) ",
form_chn: "等厚干涉",
class1: "光学",
class2: "波动光学",
class3: "",
descript1: "r:暗纹半径<br>k:暗纹级数<br>R:透镜半径",
descript2: "",
photo: "",
apply: "光干涉的条件: 频率同, 相位差恒定, 振动方向相同", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "asinθ=k 单缝衍射",
print: "asinθ=k<sub>暗</sub>λ, asinθ=(2k<sub>明</sub>+1)λ/2 ",
form_chn: "单缝衍射",
class1: "光学",
class2: "波动光学",
class3: "",
descript1: "a:缝宽<br>θ:衍射角<br>k:暗纹/亮纹级数",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "圆孔衍射 最小分辨角",
print: "sinθ=1.22λ/d ",
form_chn: "最小分辨角",
class1: "光学",
class2: "波动光学",
class3: "",
descript1: "d:通光孔径<br>θ: 最小分辨角",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


//不会分类
{formula: "p=F/S 压强",
print: "p=F/S",
form_chn: "压强",
class1: "",
class2: "",
class3: "",
descript1: "p:压强<br>F:压力<br>S:受力面积",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "P=pgh 液体压强 大气压强",
print: "P=ρgh",
form_chn: "压强",
class1: "",
class2: "",
class3: "",
descript1: "P:压强<br>ρ:密度<br>g:重力加速度<br>h:高度",
descript2: "",
photo: "",
apply: "", 
de: "F=G=mg=ρgV<br>P=F/S=ρgV/S<br>V/S=h<br>P=F/S=ρgh",
eg_q: "",
eg_a: "",
},


{formula: "p=m/v m=pv 密度",
print: "ρ=m/V",
form_chn: "密度",
class1: "",
class2: "",
class3: "",
descript1: "ρ:密度<br>m:质量<br>V:体积",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},


{formula: "",
print: "",
form_chn: "",
class1: "",
class2: "",
class3: "",
descript1: "",
descript2: "",
photo: "",
apply: "", 
de: "",
eg_q: "",
eg_a: "",
},



  
  
  
]
}})